"""Task index

Revision ID: 09084e1d0864
Revises: c03e68c7ea02
Create Date: 2024-10-21 19:17:48.926724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09084e1d0864'
down_revision: Union[str, None] = 'c03e68c7ea02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'index')
    # ### end Alembic commands ###
