"""delete unique dashboard index

Revision ID: 14daf6eb91f3
Revises: 3463788ff5d5
Create Date: 2024-10-12 19:19:24.855651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14daf6eb91f3'
down_revision: Union[str, None] = '3463788ff5d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_dashboard_project_id_index', 'dashboard', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_dashboard_project_id_index', 'dashboard', ['project_id', 'index'])
    # ### end Alembic commands ###
