"""'Dashboard'

Revision ID: 3463788ff5d5
Revises: 1b65e60ca824
Create Date: 2024-10-07 21:03:45.238706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3463788ff5d5'
down_revision: Union[str, None] = '1b65e60ca824'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard',
    sa.Column('title', sa.String(length=69), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=69), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_dashboard_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboard')),
    sa.UniqueConstraint('project_id', 'index', name=op.f('uq_dashboard_project_id_index'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboard')
    # ### end Alembic commands ###
