"""'Task'

Revision ID: 97815251a163
Revises: 14daf6eb91f3
Create Date: 2024-10-13 18:13:02.905569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97815251a163'
down_revision: Union[str, None] = '14daf6eb91f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('title', sa.String(length=69), nullable=False),
    sa.Column('dashboard_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], name=op.f('fk_task_creator_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboard.id'], name=op.f('fk_task_dashboard_id_dashboard'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task'))
    )
    op.create_table('responsible_task',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('responsible_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['responsible_id'], ['user.id'], name=op.f('fk_responsible_task_responsible_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name=op.f('fk_responsible_task_task_id_task'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_responsible_task'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responsible_task')
    op.drop_table('task')
    # ### end Alembic commands ###
