"""Unique ResponsibleTask

Revision ID: ae13cabeb27c
Revises: 09084e1d0864
Create Date: 2024-10-23 20:54:58.106329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae13cabeb27c'
down_revision: Union[str, None] = '09084e1d0864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_responsible_task_task_id_responsible_id'), 'responsible_task', ['task_id', 'responsible_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_responsible_task_task_id_responsible_id'), 'responsible_task', type_='unique')
    # ### end Alembic commands ###
