"""'User___first_name__last_name'

Revision ID: c23c43cf1dbb
Revises: 8a7b7b716a6e
Create Date: 2024-10-06 10:00:59.014173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c23c43cf1dbb'
down_revision: Union[str, None] = '8a7b7b716a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=69), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=69), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
